mfa_serial: arn:aws:iam::000000000000:mfa/my_mfa_serial # The serial ARN of the MFA token you use to log in.
default_profile: my-base-profile # Optional - A base profile that contains credentials to use when assuming roles.
roles:
  - name: something-prod-readonly
    default: yes
    arn: arn:aws:iam::000000000000:role/ReadOnly
    aliases:
      - something-prod
      - prod-readonly

  - name: something-test-developer
    arn: arn:aws:iam::111111111111:role/Developer
    aliases:
      - something-dev
      - test-dev

  - name: something-test-readonly
    arn: arn:aws:iam::111111111111:role/ReadOnly
    aliases:
      - test-readonly
