#!/usr/bin/env bash

set -eu

GOOS="${GOOS:-linux}"
GOARCH="${GOARCH:-amd64}"
GITHUB_REF="${GITHUB_REF:-""}"

function buildCommand() {
  OUTPUT_PATH="build/roo_${GOOS}_${GOARCH}"
  echo "Building: ${OUTPUT_PATH}"
  go build -v \
  -ldflags \
  "-X 'main.cacheDir=${CACHE_DIR:-""}' -X 'main.version=${GITHUB_REF##*/}'" \
  -o "${OUTPUT_PATH}${FILE_EXT:-""}" \
  "${@}"
}

# Note to self: A full list can be found by running 'go tool dist list'.

rm -v build/roo_* 2> /dev/null || true

GOOS=linux    GOARCH=amd64  CACHE_DIR="/tmp/roo"  buildCommand "${@}"
GOOS=darwin   GOARCH=amd64  CACHE_DIR="/tmp/roo"  buildCommand "${@}"
GOOS=linux    GOARCH=arm64  CACHE_DIR="/tmp/roo"  buildCommand "${@}"
GOOS=linux    GOARCH=mips64 CACHE_DIR="/tmp/roo"  buildCommand "${@}"
GOOS=windows  GOARCH=amd64  FILE_EXT=".exe"       buildCommand "${@}"

chmod 755 build/roo_*