# Creates a GitHub release
on:
  push:
    tags: ['v*']

name: Create Release

jobs:
  build:
    name: Build release artefacts
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.19
        id: go
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build project
        run: auto/build
      - name: Upload build artefacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: build/roo_*

  build_push_docker:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}

  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs:
      - build
      - build_push_docker
    steps:
      - name: Download compiled binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries
          path: build/

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          files: build/roo_*
          body: |
            Release: Version ${{ github.ref_name }}

            Docker Image: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
